/** Generated by `scripts/generate-fixtures.ts`; regenerate rather than editing. */
import type { Jwks } from '../jwks';
import { FIXTURE_KID, FIXTURE_REGISTERED_AT } from './constants';

export const DEVICE_JWKS: Jwks = {
  keys: [
    {
      kty: 'EC',
      crv: 'P-256',
      x: '6qfvhHEaxUeHW2rC7GBM2Z8cSmVETfgZOypnAY2CjRk',
      y: 'Ial9xVIgpl8XUIEspQRYt7ivy1s2IepENSL0wtxD-AM',
      kid: FIXTURE_KID,
      alg: 'ES256',
      use: 'sig',
      status: 'active',
      registered_at: FIXTURE_REGISTERED_AT,
    },
  ],
};
