/** Generated by `scripts/generate-fixtures.ts`; regenerate rather than editing. */
import { FIXTURE_ISSUER_KID } from './constants';

export const ISSUER_JWKS = {
  keys: [
    {
      kty: 'EC',
      crv: 'P-256',
      x: 'Y1J99dPeiJuo2NA_Y5HUUE2feinEIiPo9Gtf7f4nQPg',
      y: 'mkn9U6ija-q8QXUzuUzb6VseRvsgXVZOkn5hTDADPRs',
      kid: FIXTURE_ISSUER_KID,
      alg: 'ES256',
      use: 'sig',
    },
  ],
} as const;
