/** Generated by `scripts/generate-fixtures.ts`; regenerate rather than editing. */
import type { CredentialPayload, SealedCredentialEnvelope } from './sealed-credential-types';

/** Plaintext credential the envelope seals (issuer-signed, ES256, kid FIXTURE_ISSUER_KID). */
export const CREDENTIAL_PAYLOAD: CredentialPayload = {
  date_of_birth: '1990-01-15',
  sex: 'M',
  locale: 'US-CA',
  kyc_iat: 1751800000,
  exp: 1783336000,
};

export const CREDENTIAL_JWT =
  'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1ldW0tZW5yb2xsbWVudC0yMDI2In0.eyJkYXRlX29mX2JpcnRoIjoiMTk5MC0wMS0xNSIsInNleCI6Ik0iLCJsb2NhbGUiOiJVUy1DQSIsImt5Y19pYXQiOjE3NTE4MDAwMDAsImV4cCI6MTc4MzMzNjAwMH0.Wol3IeFLFj0tBlYzuYvzt-uRlwsVGIXtoitsqCd8FmuiafVatVUlG9QavjqxbH5v-KuPLMLZtKs7bnXzeJrwWg';

/**
 * Sealed to DEVICE_X25519_PUBLIC_JWK (open with DEVICE_X25519_PRIVATE_KEY_B64URL):
 * HKDF-SHA256(ECDH(epk, device), info 'meum-enrollment-v1') -> XChaCha20-Poly1305.
 */
export const SEALED_CREDENTIAL: SealedCredentialEnvelope = {
  epk: { kty: 'OKP', crv: 'X25519', x: 'WG2MlTKo6sOZ2A5SmTfCsZUIJYoLYmzQDqQRBdk25Dw' },
  nonce: 'Y7UWARK2QgBo7dP3xD-LUO10WWfZVXgO',
  ciphertext:
    'NcMUGcrl1CdG-6qQ6RsL3lKh4fI3vmzfJo5d_PpcjR_27xCKx-RBjg6l3-5ou_g4KaZeDTyKZOX4XY-9ZAiL7zJ9f5nu2pDQORNJ_t0mDnaZ3PN854ZTRErHDa12Rpm_iJ0dknXCk-GjGrmF9ykA6JYIF8nBt0QOSRyPo0f8w--BM1YaopPSvjia5i3NEaQEECIyZXdyeTipyMl64oD-Tn1WzryMPY4gKS7HqhZMhnUpDW8zT19EanIG3exO-e-FdsS2H67-K4xeilZ1G3PV5oSrFr7zSOHpLYq6vmiwveuXcrbvjcLnUxThDQWt4HldfMTxwc55tHJBA9EWmCo6MCN46AgWIkbjFfQlbe4A7DEC6T5cXVpU54x20UfhXIj6TXer7b-fSAFgrBP35RWPWz8H',
};
