/** Generated by `scripts/import-parity-fixtures.ts`; regenerate rather than editing. */
import type { SealedParityMatrix } from './sealed-receipt-parity-types';

/**
 * CryptoKit-sealed envelope matrix emitted by meum-ios `SealParityMatrixTests`
 * (TEST-ONLY key material). The device leg of the cross-stack parity harness:
 * `test/sealed-receipt-parity.test.ts` opens these with `@hpke/core` and
 * asserts the expected outcome per case plus the frozen-constant drift guard.
 */
export const SEALED_RECEIPT_PARITY: SealedParityMatrix = {
  cases: [
    {
      callback: {
        nonce: '3b46ef7d-4f6a-4c8e-9d6e-6b1a2c3d4e5f',
        receipt: {
          ct: '5dsBxaxYDY6UTZhTSQIZmrdL_dF1n76DMxRpdwSP0J53EQYJjSxFvOgVRFcVEyoQr4q4k2ZZe3jHocZDfSUrl4sODdWtQVIsQ600mv_zMKCAzyzDvhHFti4fEmQ8FGGYEKn6wX7QyZD198h5fxoGmXZcJSwTayS6wifsZ4-SmOtB6AGGLlZPJsUkX31nOjjvGNZNdsn9A3AIPv2DC8U-Nj0qMqmZHogM8VQpxAyWyOOdbLeQSDvkWuqeueyPjS3TItIn-hPUOZ-bdaLPhxeax4gG7jCmFwoLy5qdUh6Bq5wBo1EirH0r3eqL6VHIcAMipccaEmovSv-JzyHJmPnuOB-eHBnvalDaBIfcIpRMBDKobFWJxCSAfPMhvgJKWl8ucuDfnfXlwrhoxW3kaBXLEaZkorHAbeUBUvnYzrDVU7keqs5ZvflG93Kl0Bv2p9enwlnNPn0gVKYRlDfSvj3q1ItW977KpkyLN0LdAPSbDs4JqvIPwR9mGTcHMGMgfsdFoxBoDVrmbC107fplc8KktNeqA1RoWWIpO92sriF8GP3yMwKTV66T_XExWdg3KpOiAjU8cFRWflhmhrWY8gDeWemLSGXpnaX516BDBp23wi28dl-NXlJJ8lurKP3AkCsNA3kiy18oxTDfr-8JUF_GfYgOU5IY85EF_uA8GW7-shvpiGRVmAnIZThZbb9YI-n43qkva8EhaRkJI-Qo0FbVH3kjlA',
          enc: 'BP64OewRqg81Iy-QKnQRUTqgznnjnznSJ3drf_QtJhDcmobNngjmlc_xal_rRuFrRmqLar4KdouRduCISrECPOI',
          kid: 'kid_rp_enc_001',
          suite: 'HPKE-P256-SHA256-A256GCM',
          v: 2,
        },
        session_id: 'sess_fixture001',
      },
      canonical_envelope_json:
        '{"ct":"5dsBxaxYDY6UTZhTSQIZmrdL_dF1n76DMxRpdwSP0J53EQYJjSxFvOgVRFcVEyoQr4q4k2ZZe3jHocZDfSUrl4sODdWtQVIsQ600mv_zMKCAzyzDvhHFti4fEmQ8FGGYEKn6wX7QyZD198h5fxoGmXZcJSwTayS6wifsZ4-SmOtB6AGGLlZPJsUkX31nOjjvGNZNdsn9A3AIPv2DC8U-Nj0qMqmZHogM8VQpxAyWyOOdbLeQSDvkWuqeueyPjS3TItIn-hPUOZ-bdaLPhxeax4gG7jCmFwoLy5qdUh6Bq5wBo1EirH0r3eqL6VHIcAMipccaEmovSv-JzyHJmPnuOB-eHBnvalDaBIfcIpRMBDKobFWJxCSAfPMhvgJKWl8ucuDfnfXlwrhoxW3kaBXLEaZkorHAbeUBUvnYzrDVU7keqs5ZvflG93Kl0Bv2p9enwlnNPn0gVKYRlDfSvj3q1ItW977KpkyLN0LdAPSbDs4JqvIPwR9mGTcHMGMgfsdFoxBoDVrmbC107fplc8KktNeqA1RoWWIpO92sriF8GP3yMwKTV66T_XExWdg3KpOiAjU8cFRWflhmhrWY8gDeWemLSGXpnaX516BDBp23wi28dl-NXlJJ8lurKP3AkCsNA3kiy18oxTDfr-8JUF_GfYgOU5IY85EF_uA8GW7-shvpiGRVmAnIZThZbb9YI-n43qkva8EhaRkJI-Qo0FbVH3kjlA","enc":"BP64OewRqg81Iy-QKnQRUTqgznnjnznSJ3drf_QtJhDcmobNngjmlc_xal_rRuFrRmqLar4KdouRduCISrECPOI","kid":"kid_rp_enc_001","suite":"HPKE-P256-SHA256-A256GCM","v":2}',
      expect: 'valid',
      inner_receipt:
        'eyJhbGciOiJFUzI1NiIsImtpZCI6ImtpZF9maXh0dXJlMDAxIiwidHlwIjoiSldUIn0.eyJhbmFseXRpY3NfYWxsb3dlZCI6ZmFsc2UsImF1ZCI6InJwX2V4YW1wbGVfMTIzIiwiZXhwIjoxNzUxODAwMzAwLCJpYXQiOjE3NTE4MDAwMDAsImlzcyI6ImRldmljZTpraWRfZml4dHVyZTAwMSIsIm5vbmNlIjoiM2I0NmVmN2QtNGY2YS00YzhlLTlkNmUtNmIxYTJjM2Q0ZTVmIiwicHJlZGljYXRlX3Jlc3VsdCI6dHJ1ZSwicnBfa2V5X3RodW1icHJpbnQiOiJET3Z4dkppQWRJcVZXSWtGdDVoRHRDdW5YTEYwQlY0LUpHdjRmLUFMU20wIiwic2Vzc2lvbl9pZCI6InNlc3NfZml4dHVyZTAwMSJ9.OygseNkfrU_7pkjoKEneV3t-SyH9MKwqnFUatZfAg13ojPkdlCfhWL9hKsqnJwhFpHuhNPGU2EAU5w0mZlzPZA',
      name: 'valid',
      receipt_hash: 'f3d9da0cb9c1490ec4dd1dfd907e383b92733ef7e1844da17f8893d94d08e006',
    },
    {
      callback: {
        nonce: '3b46ef7d-4f6a-4c8e-9d6e-6b1a2c3d4e5f',
        receipt: {
          ct: 's3UJnNBXHzUzI9_bX1lYdE6PK-QDmR3dNifRtJb9IcHOQj1AiZl0gzp-aPVXP87uGg94lp_t69EzEQDkXjE3sXHFJxHc26l_lMLmjlqo7doHEeEXFWYitQZGDwXIhQYpoOMLgP1MuVOcgAeY0FTb2g_IWDm0rVQsh_dhFbDsKuaAJ5DKIEmXkb9z2IS4ch7e1TEIj_Yt5s5NNzdo_D2C5Nob5La1jsIsqKYAZTGies4y8BDOw9mg8-ZpSxYJZej6Rd7lqtQC2cfHDs4t6Loc3qLhrlFAjJ4NBAHiHMY6W6gGwaKgagullbB3dde4gWT8XfHgDiS0PA4SbsQOAn4xaTfUhncHbl39qykRPDb7oWJW6BzXldJ7CQrje3gfnxID3EOXLSrcBpPypLBQblXOGJkO2zXIbQCukYMrLT8DVhbHPpGXnJy0JzztwGzdSp72LxKyxOCpqXJz12WaNoLzZv5Qb91mJd2PQL6LPqEoY8iSJfz7wJ7mKXZ1xaeVqTtrJWatCSleEJN7w6Op4g2TsyBWo_PAVtIw81QHRPk014D_DluZhcbVmUiMtJ96eXV5NdPamVwgFNP8bzYjVa1SwqrX8bHce7HW8WaLW0CnFuJPWbMby5ZOD3uq6MiaM7BxDMSBpngBJtkF6LGPcAc5f2nkzgLr7Oa88y7wrHGK61jbs-S_2JSA6DCtGkQTKkyD6AxxEE4v7y3bfHUiYoVBo0xigA',
          enc: 'BNaDE85jsju_2oxGVduo17gMQsBPsP5z3ES2jJ3SWT3vRzIvyxr3zGEZTV7MpYT8zbVQ4VJiF1WVGs2T69EOA8s',
          kid: 'kid_rp_enc_001',
          suite: 'HPKE-P256-SHA256-A256GCM',
          v: 2,
        },
        session_id: 'sess_fixture001',
      },
      canonical_envelope_json:
        '{"ct":"s3UJnNBXHzUzI9_bX1lYdE6PK-QDmR3dNifRtJb9IcHOQj1AiZl0gzp-aPVXP87uGg94lp_t69EzEQDkXjE3sXHFJxHc26l_lMLmjlqo7doHEeEXFWYitQZGDwXIhQYpoOMLgP1MuVOcgAeY0FTb2g_IWDm0rVQsh_dhFbDsKuaAJ5DKIEmXkb9z2IS4ch7e1TEIj_Yt5s5NNzdo_D2C5Nob5La1jsIsqKYAZTGies4y8BDOw9mg8-ZpSxYJZej6Rd7lqtQC2cfHDs4t6Loc3qLhrlFAjJ4NBAHiHMY6W6gGwaKgagullbB3dde4gWT8XfHgDiS0PA4SbsQOAn4xaTfUhncHbl39qykRPDb7oWJW6BzXldJ7CQrje3gfnxID3EOXLSrcBpPypLBQblXOGJkO2zXIbQCukYMrLT8DVhbHPpGXnJy0JzztwGzdSp72LxKyxOCpqXJz12WaNoLzZv5Qb91mJd2PQL6LPqEoY8iSJfz7wJ7mKXZ1xaeVqTtrJWatCSleEJN7w6Op4g2TsyBWo_PAVtIw81QHRPk014D_DluZhcbVmUiMtJ96eXV5NdPamVwgFNP8bzYjVa1SwqrX8bHce7HW8WaLW0CnFuJPWbMby5ZOD3uq6MiaM7BxDMSBpngBJtkF6LGPcAc5f2nkzgLr7Oa88y7wrHGK61jbs-S_2JSA6DCtGkQTKkyD6AxxEE4v7y3bfHUiYoVBo0xigA","enc":"BNaDE85jsju_2oxGVduo17gMQsBPsP5z3ES2jJ3SWT3vRzIvyxr3zGEZTV7MpYT8zbVQ4VJiF1WVGs2T69EOA8s","kid":"kid_rp_enc_001","suite":"HPKE-P256-SHA256-A256GCM","v":2}',
      expect: 'open_failed',
      inner_receipt:
        'eyJhbGciOiJFUzI1NiIsImtpZCI6ImtpZF9maXh0dXJlMDAxIiwidHlwIjoiSldUIn0.eyJhbmFseXRpY3NfYWxsb3dlZCI6ZmFsc2UsImF1ZCI6InJwX2V4YW1wbGVfMTIzIiwiZXhwIjoxNzUxODAwMzAwLCJpYXQiOjE3NTE4MDAwMDAsImlzcyI6ImRldmljZTpraWRfZml4dHVyZTAwMSIsIm5vbmNlIjoiM2I0NmVmN2QtNGY2YS00YzhlLTlkNmUtNmIxYTJjM2Q0ZTVmIiwicHJlZGljYXRlX3Jlc3VsdCI6dHJ1ZSwicnBfa2V5X3RodW1icHJpbnQiOiI3Z1ZzbFBMMU1tMVZuREhxUG9iOHoyTWFYZGdyM2hKMXhmZzAwQzJOQnNvIiwic2Vzc2lvbl9pZCI6InNlc3NfZml4dHVyZTAwMSJ9.tRPlbXcBYv6d_CjVeW_YzifMSqvYa9y4yVUK_4phmAjAouZ0EJYuuvsYRCVhJZ-u0Bx3PLqitl5gpKNLm9hrHw',
      name: 'wrong_recipient_key',
      receipt_hash: 'cc125f8e4e8c9e9744ec010ee304b4b140908de97d5851d19b81ef020bb7b8f0',
    },
    {
      callback: {
        nonce: '3b46ef7d-4f6a-4c8e-9d6e-6b1a2c3d4e5f',
        receipt: {
          ct: '5dsBxaxYDY6UTZhTSQIZmrdL_dF1n76DMxRpdwSP0J53EQYJjSxFvOgVRFcVEyoQr4q4k2ZZe3jHocZDfSUrl4sODdWtQVIsQ600mv_zMKCAzyzDvhHFti4fEmQ8FGGYEKn6wX7QyZD198h5fxoGmXZcJSwTayS6wifsZ4-SmOtB6AGGLlZPJsUkX31nOjjvGNZNdsn9A3AIPv2DC8U-Nj0qMqmZHogM8VQpxAyWyOOdbLeQSDvkWuqeueyPjS3TItIn-hPUOZ-bdaLPhxeax4gG7jCmFwoLy5qdUh6Bq5wBo1EirH0r3eqL6VHIcAMipccaEmovSv-JzyHJmPnuOB-eHBnvalDaBIfcIpRMBDKobFWJxCSAfPMhvgJKWl8ucuDfnfXlwrhoxW3kaBXLEaZkorHAbeUBUvnYzrDVU7keqs5ZvflG93Kl0Bv2p9enwlnNPn0gVKYRlDfSvj3q1ItW977KpkyLN0LdAPSbDs4JqvIPwR9mGTcHMGMgfsdFoxBoDVrmbC107fplc8KktNeqA1RoWWIpO92sriF8GP3yMwKTV66T_XExWdg3KpOiAjU8cFRWflhmhrWY8gDeWemLSGXpnaX516BDBp23wi28dl-NXlJJ8lurKP3AkCsNA3kiy18oxTDfr-8JUF_GfYgOU5IY85EF_uA8GW7-shvpiGRVmAnIZThZbb9YI-n43qkva8EhaRkJI-Qo0FbVH3kjlA',
          enc: 'BP64OewRqg81Iy-QKnQRUTqgznnjnznSJ3drf_QtJhDcmobNngjmlc_xal_rRuFrRmqLar4KdouRduCISrECPOI',
          kid: 'kid_rp_enc_001',
          suite: 'HPKE-P256-SHA256-A256GCM',
          v: 2,
        },
        session_id: 'sess_swapped999',
      },
      canonical_envelope_json:
        '{"ct":"5dsBxaxYDY6UTZhTSQIZmrdL_dF1n76DMxRpdwSP0J53EQYJjSxFvOgVRFcVEyoQr4q4k2ZZe3jHocZDfSUrl4sODdWtQVIsQ600mv_zMKCAzyzDvhHFti4fEmQ8FGGYEKn6wX7QyZD198h5fxoGmXZcJSwTayS6wifsZ4-SmOtB6AGGLlZPJsUkX31nOjjvGNZNdsn9A3AIPv2DC8U-Nj0qMqmZHogM8VQpxAyWyOOdbLeQSDvkWuqeueyPjS3TItIn-hPUOZ-bdaLPhxeax4gG7jCmFwoLy5qdUh6Bq5wBo1EirH0r3eqL6VHIcAMipccaEmovSv-JzyHJmPnuOB-eHBnvalDaBIfcIpRMBDKobFWJxCSAfPMhvgJKWl8ucuDfnfXlwrhoxW3kaBXLEaZkorHAbeUBUvnYzrDVU7keqs5ZvflG93Kl0Bv2p9enwlnNPn0gVKYRlDfSvj3q1ItW977KpkyLN0LdAPSbDs4JqvIPwR9mGTcHMGMgfsdFoxBoDVrmbC107fplc8KktNeqA1RoWWIpO92sriF8GP3yMwKTV66T_XExWdg3KpOiAjU8cFRWflhmhrWY8gDeWemLSGXpnaX516BDBp23wi28dl-NXlJJ8lurKP3AkCsNA3kiy18oxTDfr-8JUF_GfYgOU5IY85EF_uA8GW7-shvpiGRVmAnIZThZbb9YI-n43qkva8EhaRkJI-Qo0FbVH3kjlA","enc":"BP64OewRqg81Iy-QKnQRUTqgznnjnznSJ3drf_QtJhDcmobNngjmlc_xal_rRuFrRmqLar4KdouRduCISrECPOI","kid":"kid_rp_enc_001","suite":"HPKE-P256-SHA256-A256GCM","v":2}',
      expect: 'open_failed',
      inner_receipt:
        'eyJhbGciOiJFUzI1NiIsImtpZCI6ImtpZF9maXh0dXJlMDAxIiwidHlwIjoiSldUIn0.eyJhbmFseXRpY3NfYWxsb3dlZCI6ZmFsc2UsImF1ZCI6InJwX2V4YW1wbGVfMTIzIiwiZXhwIjoxNzUxODAwMzAwLCJpYXQiOjE3NTE4MDAwMDAsImlzcyI6ImRldmljZTpraWRfZml4dHVyZTAwMSIsIm5vbmNlIjoiM2I0NmVmN2QtNGY2YS00YzhlLTlkNmUtNmIxYTJjM2Q0ZTVmIiwicHJlZGljYXRlX3Jlc3VsdCI6dHJ1ZSwicnBfa2V5X3RodW1icHJpbnQiOiJET3Z4dkppQWRJcVZXSWtGdDVoRHRDdW5YTEYwQlY0LUpHdjRmLUFMU20wIiwic2Vzc2lvbl9pZCI6InNlc3NfZml4dHVyZTAwMSJ9.OygseNkfrU_7pkjoKEneV3t-SyH9MKwqnFUatZfAg13ojPkdlCfhWL9hKsqnJwhFpHuhNPGU2EAU5w0mZlzPZA',
      name: 'swapped_session_id',
      receipt_hash: 'f3d9da0cb9c1490ec4dd1dfd907e383b92733ef7e1844da17f8893d94d08e006',
    },
    {
      callback: {
        nonce: '9d1a5f22-0c4b-4e7a-8b3c-5e6f7a8b9c0d',
        receipt: {
          ct: '5dsBxaxYDY6UTZhTSQIZmrdL_dF1n76DMxRpdwSP0J53EQYJjSxFvOgVRFcVEyoQr4q4k2ZZe3jHocZDfSUrl4sODdWtQVIsQ600mv_zMKCAzyzDvhHFti4fEmQ8FGGYEKn6wX7QyZD198h5fxoGmXZcJSwTayS6wifsZ4-SmOtB6AGGLlZPJsUkX31nOjjvGNZNdsn9A3AIPv2DC8U-Nj0qMqmZHogM8VQpxAyWyOOdbLeQSDvkWuqeueyPjS3TItIn-hPUOZ-bdaLPhxeax4gG7jCmFwoLy5qdUh6Bq5wBo1EirH0r3eqL6VHIcAMipccaEmovSv-JzyHJmPnuOB-eHBnvalDaBIfcIpRMBDKobFWJxCSAfPMhvgJKWl8ucuDfnfXlwrhoxW3kaBXLEaZkorHAbeUBUvnYzrDVU7keqs5ZvflG93Kl0Bv2p9enwlnNPn0gVKYRlDfSvj3q1ItW977KpkyLN0LdAPSbDs4JqvIPwR9mGTcHMGMgfsdFoxBoDVrmbC107fplc8KktNeqA1RoWWIpO92sriF8GP3yMwKTV66T_XExWdg3KpOiAjU8cFRWflhmhrWY8gDeWemLSGXpnaX516BDBp23wi28dl-NXlJJ8lurKP3AkCsNA3kiy18oxTDfr-8JUF_GfYgOU5IY85EF_uA8GW7-shvpiGRVmAnIZThZbb9YI-n43qkva8EhaRkJI-Qo0FbVH3kjlA',
          enc: 'BP64OewRqg81Iy-QKnQRUTqgznnjnznSJ3drf_QtJhDcmobNngjmlc_xal_rRuFrRmqLar4KdouRduCISrECPOI',
          kid: 'kid_rp_enc_001',
          suite: 'HPKE-P256-SHA256-A256GCM',
          v: 2,
        },
        session_id: 'sess_fixture001',
      },
      canonical_envelope_json:
        '{"ct":"5dsBxaxYDY6UTZhTSQIZmrdL_dF1n76DMxRpdwSP0J53EQYJjSxFvOgVRFcVEyoQr4q4k2ZZe3jHocZDfSUrl4sODdWtQVIsQ600mv_zMKCAzyzDvhHFti4fEmQ8FGGYEKn6wX7QyZD198h5fxoGmXZcJSwTayS6wifsZ4-SmOtB6AGGLlZPJsUkX31nOjjvGNZNdsn9A3AIPv2DC8U-Nj0qMqmZHogM8VQpxAyWyOOdbLeQSDvkWuqeueyPjS3TItIn-hPUOZ-bdaLPhxeax4gG7jCmFwoLy5qdUh6Bq5wBo1EirH0r3eqL6VHIcAMipccaEmovSv-JzyHJmPnuOB-eHBnvalDaBIfcIpRMBDKobFWJxCSAfPMhvgJKWl8ucuDfnfXlwrhoxW3kaBXLEaZkorHAbeUBUvnYzrDVU7keqs5ZvflG93Kl0Bv2p9enwlnNPn0gVKYRlDfSvj3q1ItW977KpkyLN0LdAPSbDs4JqvIPwR9mGTcHMGMgfsdFoxBoDVrmbC107fplc8KktNeqA1RoWWIpO92sriF8GP3yMwKTV66T_XExWdg3KpOiAjU8cFRWflhmhrWY8gDeWemLSGXpnaX516BDBp23wi28dl-NXlJJ8lurKP3AkCsNA3kiy18oxTDfr-8JUF_GfYgOU5IY85EF_uA8GW7-shvpiGRVmAnIZThZbb9YI-n43qkva8EhaRkJI-Qo0FbVH3kjlA","enc":"BP64OewRqg81Iy-QKnQRUTqgznnjnznSJ3drf_QtJhDcmobNngjmlc_xal_rRuFrRmqLar4KdouRduCISrECPOI","kid":"kid_rp_enc_001","suite":"HPKE-P256-SHA256-A256GCM","v":2}',
      expect: 'open_failed',
      inner_receipt:
        'eyJhbGciOiJFUzI1NiIsImtpZCI6ImtpZF9maXh0dXJlMDAxIiwidHlwIjoiSldUIn0.eyJhbmFseXRpY3NfYWxsb3dlZCI6ZmFsc2UsImF1ZCI6InJwX2V4YW1wbGVfMTIzIiwiZXhwIjoxNzUxODAwMzAwLCJpYXQiOjE3NTE4MDAwMDAsImlzcyI6ImRldmljZTpraWRfZml4dHVyZTAwMSIsIm5vbmNlIjoiM2I0NmVmN2QtNGY2YS00YzhlLTlkNmUtNmIxYTJjM2Q0ZTVmIiwicHJlZGljYXRlX3Jlc3VsdCI6dHJ1ZSwicnBfa2V5X3RodW1icHJpbnQiOiJET3Z4dkppQWRJcVZXSWtGdDVoRHRDdW5YTEYwQlY0LUpHdjRmLUFMU20wIiwic2Vzc2lvbl9pZCI6InNlc3NfZml4dHVyZTAwMSJ9.OygseNkfrU_7pkjoKEneV3t-SyH9MKwqnFUatZfAg13ojPkdlCfhWL9hKsqnJwhFpHuhNPGU2EAU5w0mZlzPZA',
      name: 'swapped_nonce',
      receipt_hash: 'f3d9da0cb9c1490ec4dd1dfd907e383b92733ef7e1844da17f8893d94d08e006',
    },
    {
      callback: {
        nonce: '3b46ef7d-4f6a-4c8e-9d6e-6b1a2c3d4e5f',
        receipt: {
          ct: 'suwwJ0AstKFFPk72w2BcFB8x9YhynauNzoWvXLYIUFriZxd-lwErTM5Q5HnqCMSPPNDZdZTmp5BBNhoQnApNGQN-tqOHFsecWTRfN-8tDo0ASbheWHNXxXruREmlXtzwGwy5W_bAWPMzqLTfCk5DgXsyqtmv6l4uh7wRN8_UlwdTxpmi1iBKw5iZ-dQYQKiXoREHHzSLaD0FWr5njfQNZOSBm-Jfi_J7gNeTLX4_i2feCNMCH_Vz6Q99U7SvGMcuVUf9WOtx8bRSlT0qVPOiCpFTz-4Cs9mSsktZiIYGhCVgXCnx5xOwFo04kEzckr2fHhlpQCKh7_Lt4SClp95Um1UqFqGdGOT8HtX-cXaINaxnSvTUzLDM02pCMScWjnlnV_RilGyHzhSXo6h_lunHeFWZoIN4bk2O0tq9Rldb_-JBoudnJM_LnHOJZE8tspMpLgxQ9MTA_AQO4wa-wLNo7deEqbCbHamKHKrG46rYfm6eNBECDFqZXnnXP7eyK2J-BGNpw7kfCpxApVYeIzPhQqfe7FMKMGSmvgWKNH6HDNeTLOZAZPRDEJ6mUUqW2Sk-CVxE0rlemizjBoDNqPwwiL-i8fUwaTUsaxs-mSfKMnpx-m2b3sFDc9ZsTJEvGZRWvhcsncmkBpT0quIy-1zgLqdG3AD5JDvDG-89stJZYNAglfbgk1v1IFftKlzpWANtPX8jCOYXMU6aXgWsJx6klJZVDQ',
          enc: 'BCpcoydb45aiMpx0A2dl4YaEVmTIc3LttW2XFVg41P_xeAIQ6Zn7KTfm-XG6Ij86X9NwM3Jr4tjaKukYdCQrGkc',
          kid: 'kid_rp_enc_000',
          suite: 'HPKE-P256-SHA256-A256GCM',
          v: 2,
        },
        session_id: 'sess_fixture001',
      },
      canonical_envelope_json:
        '{"ct":"suwwJ0AstKFFPk72w2BcFB8x9YhynauNzoWvXLYIUFriZxd-lwErTM5Q5HnqCMSPPNDZdZTmp5BBNhoQnApNGQN-tqOHFsecWTRfN-8tDo0ASbheWHNXxXruREmlXtzwGwy5W_bAWPMzqLTfCk5DgXsyqtmv6l4uh7wRN8_UlwdTxpmi1iBKw5iZ-dQYQKiXoREHHzSLaD0FWr5njfQNZOSBm-Jfi_J7gNeTLX4_i2feCNMCH_Vz6Q99U7SvGMcuVUf9WOtx8bRSlT0qVPOiCpFTz-4Cs9mSsktZiIYGhCVgXCnx5xOwFo04kEzckr2fHhlpQCKh7_Lt4SClp95Um1UqFqGdGOT8HtX-cXaINaxnSvTUzLDM02pCMScWjnlnV_RilGyHzhSXo6h_lunHeFWZoIN4bk2O0tq9Rldb_-JBoudnJM_LnHOJZE8tspMpLgxQ9MTA_AQO4wa-wLNo7deEqbCbHamKHKrG46rYfm6eNBECDFqZXnnXP7eyK2J-BGNpw7kfCpxApVYeIzPhQqfe7FMKMGSmvgWKNH6HDNeTLOZAZPRDEJ6mUUqW2Sk-CVxE0rlemizjBoDNqPwwiL-i8fUwaTUsaxs-mSfKMnpx-m2b3sFDc9ZsTJEvGZRWvhcsncmkBpT0quIy-1zgLqdG3AD5JDvDG-89stJZYNAglfbgk1v1IFftKlzpWANtPX8jCOYXMU6aXgWsJx6klJZVDQ","enc":"BCpcoydb45aiMpx0A2dl4YaEVmTIc3LttW2XFVg41P_xeAIQ6Zn7KTfm-XG6Ij86X9NwM3Jr4tjaKukYdCQrGkc","kid":"kid_rp_enc_000","suite":"HPKE-P256-SHA256-A256GCM","v":2}',
      expect: 'valid',
      inner_receipt:
        'eyJhbGciOiJFUzI1NiIsImtpZCI6ImtpZF9maXh0dXJlMDAxIiwidHlwIjoiSldUIn0.eyJhbmFseXRpY3NfYWxsb3dlZCI6ZmFsc2UsImF1ZCI6InJwX2V4YW1wbGVfMTIzIiwiZXhwIjoxNzUxODAwMzAwLCJpYXQiOjE3NTE4MDAwMDAsImlzcyI6ImRldmljZTpraWRfZml4dHVyZTAwMSIsIm5vbmNlIjoiM2I0NmVmN2QtNGY2YS00YzhlLTlkNmUtNmIxYTJjM2Q0ZTVmIiwicHJlZGljYXRlX3Jlc3VsdCI6dHJ1ZSwicnBfa2V5X3RodW1icHJpbnQiOiJwd3pTNW9JdGFZZG9qZUlhTVpqd3ZTMWxwa3JaWHJ1QWQza2w0dzZXejVrIiwic2Vzc2lvbl9pZCI6InNlc3NfZml4dHVyZTAwMSJ9.D2MaroFxgSjHbkvlzttwN8BqoZ66g8fejqX8HRYNpP58LjJXrZmInQmp455we6URiIbcoRhkI55rwmhMEdkX_w',
      name: 'superseded_key',
      receipt_hash: '7b0359faec21cfb4ca6b618dd5702acc63ab207cadf822e237f0f97219296dff',
    },
  ],
  device_jwk: {
    alg: 'ES256',
    crv: 'P-256',
    kid: 'kid_fixture001',
    kty: 'EC',
    use: 'sig',
    x: '6qfvhHEaxUeHW2rC7GBM2Z8cSmVETfgZOypnAY2CjRk',
    y: 'Ial9xVIgpl8XUIEspQRYt7ivy1s2IepENSL0wtxD-AM',
  },
  meta: {
    aad_separator: '|',
    aad_utf8: 'sess_fixture001|3b46ef7d-4f6a-4c8e-9d6e-6b1a2c3d4e5f',
    audience: 'rp_example_123',
    iat: 1751800000,
    info: 'meum:sealed-receipt:v2',
    nonce: '3b46ef7d-4f6a-4c8e-9d6e-6b1a2c3d4e5f',
    session_id: 'sess_fixture001',
    suite: 'HPKE-P256-SHA256-A256GCM',
    v: 2,
  },
  recipients: {
    current: {
      jwk: {
        crv: 'P-256',
        d: 'ya-p2EW6dRZrXCFXZ7HWk05Qw9s26JsSe4piKxIPZyE',
        kty: 'EC',
        x: 'YP7UuiVanTHJYet0xjVtaMBJuJI7Yfps5mliLmDyn7Y',
        y: 'eQP-EAi4vJmkGunpVii8ZPLxsgwtfp9Rd6PClNRGIpk',
      },
      kid: 'kid_rp_enc_001',
      thumbprint: 'DOvxvJiAdIqVWIkFt5hDtCunXLF0BV4-JGv4f-ALSm0',
    },
    superseded: {
      jwk: {
        crv: 'P-256',
        d: 'gMnSj25Ara8dvdviDVD8V31xrVWsKXjtb4DFCwGFYmU',
        kty: 'EC',
        x: 'W5wgafscz2dWnBiA1F5Mj-nyt6Dsz53A1Ao4CCWrP8U',
        y: 'i0j-JznVYFLwvVMr1Na9Q1x1wb2K8oO_yVtxDdxQQPk',
      },
      kid: 'kid_rp_enc_000',
      thumbprint: 'pwzS5oItaYdojeIaMZjwvS1lpkrZXruAd3kl4w6Wz5k',
    },
  },
};
