/** Generated by `scripts/generate-fixtures.ts`; regenerate rather than editing. */
/**
 * TEST-ONLY key material. Never use these keys outside fixtures.
 */
export const DEVICE_SIGNING_PRIVATE_JWK = {
  crv: 'P-256',
  d: '78M1GCq-H0y5etAPpJXFLlIyIx1LRbCwuMvuZIolPQQ',
  ext: true,
  key_ops: ['sign'],
  kty: 'EC',
  x: '6qfvhHEaxUeHW2rC7GBM2Z8cSmVETfgZOypnAY2CjRk',
  y: 'Ial9xVIgpl8XUIEspQRYt7ivy1s2IepENSL0wtxD-AM',
} as const;

export const DEVICE_SIGNING_PUBLIC_JWK = {
  crv: 'P-256',
  ext: true,
  key_ops: ['verify'],
  kty: 'EC',
  x: '6qfvhHEaxUeHW2rC7GBM2Z8cSmVETfgZOypnAY2CjRk',
  y: 'Ial9xVIgpl8XUIEspQRYt7ivy1s2IepENSL0wtxD-AM',
} as const;

export const ISSUER_SIGNING_PRIVATE_JWK = {
  crv: 'P-256',
  d: 'shcLI4wIQkr-AC6mUdaHLipLOqj81mI-xIxIk3WRvR8',
  ext: true,
  key_ops: ['sign'],
  kty: 'EC',
  x: 'Y1J99dPeiJuo2NA_Y5HUUE2feinEIiPo9Gtf7f4nQPg',
  y: 'mkn9U6ija-q8QXUzuUzb6VseRvsgXVZOkn5hTDADPRs',
} as const;

export const DEVICE_X25519_PRIVATE_KEY_B64URL = '8ZrSTiWs0VBoRbFW0RO3a9oD9GliYfCAhz8_0HuizGA';

export const DEVICE_X25519_PUBLIC_JWK = {
  kty: 'OKP',
  crv: 'X25519',
  x: 'dk0ADDPLvpC6IV1Xp1Ouxr_uUTIMktx3_-imgVaMaG4',
} as const;
