/**
 * One-shot generator for the committed fixture modules in `src/fixtures/`.
 * Run with `bun packages/verify/scripts/generate-fixtures.ts` from the repo
 * root; the outputs are deterministic once committed (fresh runs mint fresh
 * key material, so regenerate only when the fixture set must change).
 *
 * `@noble/*` is a devDependency used only here; the shipped verifier stays
 * zero-dependency (WebCrypto).
 */
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import { x25519 } from '@noble/curves/ed25519.js';
import { hkdf } from '@noble/hashes/hkdf.js';
import { sha256 } from '@noble/hashes/sha2.js';
import {
  FIXTURE_EXP,
  FIXTURE_IAT,
  FIXTURE_ISSUER_KID,
  FIXTURE_KID,
  FIXTURE_NONCE,
  FIXTURE_NOW,
  FIXTURE_RP_ID,
  FIXTURE_SESSION_ID,
  FIXTURE_UNKNOWN_KID,
  FIXTURE_WRONG_NONCE,
  FIXTURE_WRONG_RP_ID,
} from '../src/fixtures/constants';
import type { ReceiptPayload } from '../src/receipt-types';

const FIXTURES_DIR = new URL('../src/fixtures/', import.meta.url).pathname;

function toB64Url(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('base64url');
}

function utf8ToB64Url(text: string): string {
  return Buffer.from(text, 'utf8').toString('base64url');
}

type Jwk = { kty?: string; crv?: string; x?: string; y?: string; d?: string };

async function generateP256(): Promise<{ privateJwk: Jwk; publicJwk: Jwk; privateKey: CryptoKey }> {
  const pair = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
  const privateJwk = await crypto.subtle.exportKey('jwk', pair.privateKey);
  const publicJwk = await crypto.subtle.exportKey('jwk', pair.publicKey);
  return { privateJwk, publicJwk, privateKey: pair.privateKey };
}

async function signJwt(
  header: Record<string, unknown>,
  payload: Record<string, unknown>,
  privateKey: CryptoKey,
): Promise<string> {
  const signingInput = `${utf8ToB64Url(JSON.stringify(header))}.${utf8ToB64Url(JSON.stringify(payload))}`;
  const signature = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    privateKey,
    new TextEncoder().encode(signingInput),
  );
  return `${signingInput}.${toB64Url(new Uint8Array(signature))}`;
}

function tamperSignature(jwt: string): string {
  const lastChar = jwt.at(-1);
  const replacement = lastChar === 'A' ? 'B' : 'A';
  return jwt.slice(0, -1) + replacement;
}

const GENERATED_NOTE = '/** Generated by `scripts/generate-fixtures.ts`; regenerate rather than editing. */';

async function writeFixture(fileName: string, content: string): Promise<void> {
  await Bun.write(`${FIXTURES_DIR}${fileName}`, `${GENERATED_NOTE}\n${content}`);
  console.log(`wrote src/fixtures/${fileName}`);
}

const device = await generateP256();
const issuer = await generateP256();

const receiptHeader = { alg: 'ES256', typ: 'JWT', kid: FIXTURE_KID };
const receiptPayload: ReceiptPayload = {
  iss: `device:${FIXTURE_KID}`,
  aud: FIXTURE_RP_ID,
  session_id: FIXTURE_SESSION_ID,
  nonce: FIXTURE_NONCE,
  iat: FIXTURE_IAT,
  exp: FIXTURE_EXP,
  predicate_result: true,
  analytics_allowed: false,
};

const validReceipt = await signJwt(receiptHeader, { ...receiptPayload }, device.privateKey);
const badSignature = tamperSignature(validReceipt);
const wrongAud = await signJwt(receiptHeader, { ...receiptPayload, aud: FIXTURE_WRONG_RP_ID }, device.privateKey);
const expired = await signJwt(
  receiptHeader,
  { ...receiptPayload, iat: FIXTURE_NOW - 900, exp: FIXTURE_NOW - 600 },
  device.privateKey,
);
const wrongNonce = await signJwt(receiptHeader, { ...receiptPayload, nonce: FIXTURE_WRONG_NONCE }, device.privateKey);
const predicateFalse = await signJwt(receiptHeader, { ...receiptPayload, predicate_result: false }, device.privateKey);
const unknownKid = await signJwt(
  { ...receiptHeader, kid: FIXTURE_UNKNOWN_KID },
  { ...receiptPayload, iss: `device:${FIXTURE_UNKNOWN_KID}` },
  device.privateKey,
);

const credentialPayload = {
  date_of_birth: '1990-01-15',
  sex: 'M',
  locale: 'US-CA',
  kyc_iat: FIXTURE_IAT,
  exp: FIXTURE_IAT + 31_536_000,
};
const credentialJwt = await signJwt(
  { alg: 'ES256', typ: 'JWT', kid: FIXTURE_ISSUER_KID },
  credentialPayload,
  issuer.privateKey,
);

const deviceX25519Private = x25519.utils.randomPrivateKey();
const deviceX25519Public = x25519.getPublicKey(deviceX25519Private);
const backendEphemeralPrivate = x25519.utils.randomPrivateKey();
const backendEphemeralPublic = x25519.getPublicKey(backendEphemeralPrivate);

const sharedSecret = x25519.getSharedSecret(backendEphemeralPrivate, deviceX25519Public);
const sealKey = hkdf(sha256, sharedSecret, undefined, 'meum-enrollment-v1', 32);
const sealNonce = crypto.getRandomValues(new Uint8Array(24));
const ciphertext = xchacha20poly1305(sealKey, sealNonce).encrypt(new TextEncoder().encode(credentialJwt));

await writeFixture(
  'test-keys.ts',
  `/**
 * TEST-ONLY key material. Never use these keys outside fixtures.
 */
export const DEVICE_SIGNING_PRIVATE_JWK = ${JSON.stringify(device.privateJwk, null, 2)} as const;

export const DEVICE_SIGNING_PUBLIC_JWK = ${JSON.stringify(device.publicJwk, null, 2)} as const;

export const ISSUER_SIGNING_PRIVATE_JWK = ${JSON.stringify(issuer.privateJwk, null, 2)} as const;

export const DEVICE_X25519_PRIVATE_KEY_B64URL = '${toB64Url(deviceX25519Private)}';

export const DEVICE_X25519_PUBLIC_JWK = ${JSON.stringify({ kty: 'OKP', crv: 'X25519', x: toB64Url(deviceX25519Public) }, null, 2)} as const;
`,
);

await writeFixture(
  'device-jwks.ts',
  `import type { Jwks } from '../jwks';
import { FIXTURE_KID, FIXTURE_REGISTERED_AT } from './constants';

export const DEVICE_JWKS: Jwks = {
  keys: [
    {
      kty: 'EC',
      crv: 'P-256',
      x: '${device.publicJwk.x}',
      y: '${device.publicJwk.y}',
      kid: FIXTURE_KID,
      alg: 'ES256',
      use: 'sig',
      status: 'active',
    },
  ],
};
`,
);

await writeFixture(
  'issuer-jwks.ts',
  `import { FIXTURE_ISSUER_KID } from './constants';

export const ISSUER_JWKS = {
  keys: [
    {
      kty: 'EC',
      crv: 'P-256',
      x: '${issuer.publicJwk.x}',
      y: '${issuer.publicJwk.y}',
      kid: FIXTURE_ISSUER_KID,
      alg: 'ES256',
      use: 'sig',
    },
  ],
} as const;
`,
);

await writeFixture(
  'valid-receipt.ts',
  `/** Verifies with DEVICE_JWKS at FIXTURE_NOW for aud FIXTURE_RP_ID + nonce FIXTURE_NONCE. */
export const VALID_RECEIPT = '${validReceipt}';
`,
);

const invalidFixtures: Array<[string, string, string, string]> = [
  ['invalid-bad-signature.ts', 'INVALID_BAD_SIGNATURE', badSignature, 'Last signature character flipped.'],
  ['invalid-wrong-aud.ts', 'INVALID_WRONG_AUD', wrongAud, 'aud is FIXTURE_WRONG_RP_ID.'],
  ['invalid-expired.ts', 'INVALID_EXPIRED', expired, 'exp is 600s before FIXTURE_NOW.'],
  ['invalid-wrong-nonce.ts', 'INVALID_WRONG_NONCE', wrongNonce, 'nonce is FIXTURE_WRONG_NONCE.'],
  [
    'invalid-predicate-false.ts',
    'INVALID_PREDICATE_FALSE',
    predicateFalse,
    'Well-signed receipt with predicate_result:false.',
  ],
  ['invalid-unknown-kid.ts', 'INVALID_UNKNOWN_KID', unknownKid, 'Header kid FIXTURE_UNKNOWN_KID is not in the JWKS.'],
];

for (const [file, name, jwt, note] of invalidFixtures) {
  await writeFixture(
    file,
    `/** ${note} */
export const ${name} = '${jwt}';
`,
  );
}

await writeFixture(
  'sealed-credential.ts',
  `import type { CredentialPayload, SealedCredentialEnvelope } from './sealed-credential-types';

/** Plaintext credential the envelope seals (issuer-signed, ES256, kid FIXTURE_ISSUER_KID). */
export const CREDENTIAL_PAYLOAD: CredentialPayload = ${JSON.stringify(credentialPayload, null, 2)};

export const CREDENTIAL_JWT = '${credentialJwt}';

/**
 * Sealed to DEVICE_X25519_PUBLIC_JWK (open with DEVICE_X25519_PRIVATE_KEY_B64URL):
 * HKDF-SHA256(ECDH(epk, device), info 'meum-enrollment-v1') -> XChaCha20-Poly1305.
 */
export const SEALED_CREDENTIAL: SealedCredentialEnvelope = {
  epk: { kty: 'OKP', crv: 'X25519', x: '${toB64Url(backendEphemeralPublic)}' },
  nonce: '${toB64Url(sealNonce)}',
  ciphertext: '${toB64Url(ciphertext)}',
};
`,
);

console.log('fixture generation complete');
