/**
 * Imports the CryptoKit-emitted sealed-receipt parity matrix into the
 * committed fixture module `src/fixtures/sealed-receipt-parity.ts`. The
 * emitter is the meum-ios MeumCore test suite:
 *
 *   MEUM_SEAL_PARITY_OUT=<path>.json swift test --filter SealParityMatrixTests
 *   bun packages/verify/scripts/import-parity-fixtures.ts <path>.json
 *   bun run format
 *
 * The output is deterministic once committed (each Swift emit mints fresh
 * HPKE ephemerals and ECDSA nonces, so regenerate only when the matrix must
 * change). Shape errors fail here rather than surfacing as opaque test
 * failures downstream.
 */
import type { SealedParityMatrix } from '../src/fixtures/sealed-receipt-parity-types';

const EXPECTED_CASES = ['valid', 'wrong_recipient_key', 'swapped_session_id', 'swapped_nonce', 'superseded_key'];

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('usage: bun packages/verify/scripts/import-parity-fixtures.ts <matrix.json>');
  process.exit(2);
}

const matrix = (await Bun.file(inputPath).json()) as SealedParityMatrix;

const problems: string[] = [];
if (typeof matrix.meta?.suite !== 'string' || typeof matrix.meta?.info !== 'string') {
  problems.push('meta is missing the suite/info bindings');
}
for (const slot of ['current', 'superseded'] as const) {
  if (typeof matrix.recipients?.[slot]?.jwk?.d !== 'string') {
    problems.push(`recipients.${slot} is missing its private JWK`);
  }
}
const caseNames = (matrix.cases ?? []).map((candidate) => candidate.name);
if ([...caseNames].sort().join(',') !== [...EXPECTED_CASES].sort().join(',')) {
  problems.push(`cases are [${caseNames.join(', ')}], expected [${EXPECTED_CASES.join(', ')}]`);
}
if (problems.length > 0) {
  console.error(`refusing to import ${inputPath}:`);
  for (const problem of problems) {
    console.error(`  - ${problem}`);
  }
  process.exit(1);
}

const outUrl = new URL('../src/fixtures/sealed-receipt-parity.ts', import.meta.url);
const content = `/** Generated by \`scripts/import-parity-fixtures.ts\`; regenerate rather than editing. */
import type { SealedParityMatrix } from './sealed-receipt-parity-types';

/**
 * CryptoKit-sealed envelope matrix emitted by meum-ios \`SealParityMatrixTests\`
 * (TEST-ONLY key material). The device leg of the cross-stack parity harness:
 * \`test/sealed-receipt-parity.test.ts\` opens these with \`@hpke/core\` and
 * asserts the expected outcome per case plus the frozen-constant drift guard.
 */
export const SEALED_RECEIPT_PARITY: SealedParityMatrix = ${JSON.stringify(matrix, null, 2)};
`;
await Bun.write(outUrl.pathname, content);
console.log(`wrote src/fixtures/sealed-receipt-parity.ts (${matrix.cases.length} cases)`);
